#ifndef _COMMANDS_PROCESSOR_H_
#define _COMMANDS_PROCESSOR_H_

#include "commands-processor-private.h"
#include "commands-processor-impl-private.h"

#define COMMANDS_PROCESSOR_DEFINE(_NAME, _IN_COMMAND_TYPE, _OUT_COMMAND_TYPE)  	\
	_COMMANDS_PROCESSOR_DEFINE(_NAME, _IN_COMMAND_TYPE, _OUT_COMMAND_TYPE)

#define COMMANDS_PROCESSOR_IMPLEMENTATION(_NAME, _IN_COMMAND_TYPE, _OUT_COMMAND_TYPE)  	\
	_COMMANDS_PROCESSOR_IMPLEMENTATION(_NAME, _IN_COMMAND_TYPE, _OUT_COMMAND_TYPE)

#endif
